# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: User Docs
description: Developer documentation for Cebola project
baseurl: "/Cebola-userdocs"
url: "https://novaicariusq.github.io"

cebola_url: "http://178.105.247.125:8080/"

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

permalink: pretty

# Theme settings
theme: just-the-docs
color_scheme: cebola-light
favicon_ico: "/assets/images/favicon.ico"
mermaid:
  version: "11.15.0"

aux_links:
  "Go Back to The Site":
    - "http://178.105.247.125:8080/"

aux_links_new_tab: true

# Footer
back_to_top: true
back_to_top_text: "Back to top"

# gh_edit_link: true
# gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_repository: "https://github.com/novAIcariusQ/Cebola-devdocs"
# gh_edit_branch: "main"
# gh_edit_view_mode: "tree"

# Color style
callouts:
  highlight:
    color: yellow
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple
  warning:
    title: Warning
    color: yellow
  caution:
    title: Caution
    color: red

# plugins:
#   - jekyll-spaceship

# jekyll-spaceship:
#   processors:
#     - mermaid-processor
#     - plantuml-processor

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - "devbox*"
  - .devbox
  - .ruby-lsp
  - ".git*"
