name: Build Jekyll

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true   # Caches gems for faster builds

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6

      - name: Install Gems
        run: bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --destination ./_site
        env:
          JEKYLL_ENV: production
